# Generated by Django 5.2.1 on 2025-05-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='names',
            new_name='nam',
        ),
    ]
