# Generated by Django 5.2.1 on 2025-05-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nam',
        ),
    ]
